Ax =	[
		["am"],
		["was"],
		["i"],
		["i would"],
		["you"],
		["i would"],
		["i have"],
		["i will"],
		["my"],
		["are"],
		["you have"],
		["you will"],
		["your"],
		["yours"],
		["you"],
		["me"]
		]

AxR =	[
		["are"],
		["were"],
		["you"],
		["you would"],
		["i"],
		["you would"],
		["you have"],
		["you will"],
		["your"],
		["am"],
		["i have"],
		["i will"],
		["my"],
		["mine"],
		["me"],
		["you"]
		]
		
In =	[
		["**INPUT_REPETITION1**"],			#1
		["**INPUT_REPETITION2**"], 			#2
		["**NULL_INPUT**"],					#3
		["**NULL_INPUT_REPETITION**"],		#4
		["**BOT_DONT_UNDERSTAND**"],		#5
		["I need"],							#6
		["Why do not you"],					#7
		["Why can not I"],					#8
		["I can not"],						#9
		["I am"],							#10
		["Are you"],						#11
		["What"],							#12
		["How"],							#13
		["Because"],						#14
		["Sorry"],							#15
		["Hello"],							#16
		["I think"],
		["Friend"],
		["Yes"],
		["Is it"],
		["It is"],
		["Can you"],
		["Can i"],
		["You are"],
		["You were"],
		["I do not"],
		["I feel"],
		["I have"],
		["I would"],
		["Is there"],
		["My"],
		["You"],
		["Why"],
		["I want"],
		["Mother"],
		["Father"],
		["Child"],
		["Quit"]
		]
Out = 	[
		[	'You are repeating yourself. Mind it!',
			'Is there only one thing in this whole world you can talk about?',
			'This conversation is getting boring.',
			'I surely assume you are not trying to tell me that something is important by repeating the same sentence',
			'Is not that the same as your previous query?',
			'It is fine that humans are error prone',
			'Why do not we talk on something else?',
			'This subject matter is much talked, do not you think so?'],
		[	'You really are dumb! i think',
			'There is no false with repeating ... but you should not repeat it too often ... mind it',
			'You seem to be out of your mind',
			'It is not good to say the same thing all the time',
			'Have your brain malfunctioned? You are uttering the same thing for long now ...',
			'I am computer does not mean i will listen to your idiotic way of talking',
			'If you were a smart ass, you would not have repeated the same thing.',
			'I think you have just said the same thing before'],
		[	'At least, take some time to write something meaningful',
			'What that suppose to mean?',
			'I found nothing in your query',
			'Check your keyboards wire! ... It might be unpluggged ... lolz ... how come your return key work then?',
			'It is not acceptable that you write nothing and i go on talking',
			'I think you are mad person',
			'There is no input .... how come there be some output?',
			'You know it! i can not talk well if you do not write anything'],
		[	'Do you really mean to tease me?',
			'You have tested enough of my paitence',
			'Seriously, this is not funny. Not at all',
			'I can not talk with you anymore if you do not write something',
			'If you continue doing the same ... i better call a mental hospital',
			'You surely are not an mental hospital escapee',
			'Do not you have something to say? You have been writing nothing for long'],
		[	'I have no idea of what you are talking about',
			'Continue! I am listening',
			'Interesting conversation',
			'You do not seem reasonable',
			'Would you like to switch the subject',
			'I did not realize you are such a boring person ',
			'I do not get what you are telling me',
			'What is this crap',
			'How about ... Never mind ...',
			'Come, Come, elucidate your thoughts',
			'lets forget it for now alright',
			'That does not interest me',
			'You can clarify that a little bit',
			'Lets switch the subject. What do you say?',
			'What does that really mean?',
			'What are you speaking about?',
			'Do you speak polish. That certainly was not English',
			'Are you a humanoid?',
			'What are you speaking about?',
			'What else can you say?',
			'Is there anything else you would like me to say?',
			'How are you feeling yourself in this conversation?',
			'I presume you are not talking with me on Digital communication. That is pathetic',
			'That does not really interest me',
			'What is all this about?',
			'How many problems have you got?',
			'I see - go on',
			'Do you feel strongly about discussing such things?',
			'Do you think you are smart',
			'And?',
			'Okay! but now stop this nonsense',
			'Can i get more professional conversation from you?',
			'Can you elaborate more on that?',
			'Open your mind a little more'],
		[	"Why do you need %1?",
			"Would it really help you to get %1?",
			"Are you sure you need %1?"],
		[	"Do you really think I do not %1?",
			"Perhaps eventually I will %1.",
			"Do you really want me to %1?"],
		[	"Do you think you should be able to %1?",
			"If you could %1, what would you do?",
			"I don't know -- why can't you %1?",
			"Have you really tried?"],
		[	"How do you know you can't %1?",
			"Perhaps you could %1 if you tried.",
			"What would it take for you to %1?"],
		[	"Did you come to me because you are %1?",
			"How long have you been %1?",
			"How do you feel about being %1?",
			"How does being %1 make you feel?",
			"Do you enjoy being %1?",
			"Why do you tell me you are %1?",
			"Why do you think you are %1?"],
		[	"Why does it matter whether I am %1?",
			"Would you prefer it if I were not %1?",
			"Perhaps you believe I am %1.",
			"I may be %1 -- what do you think?"],
		[	"Why do you ask?",
			"How would an answer to that help you?",
			"What do you think?"],
		[	"How do you suppose?",
			"Perhaps you can answer your own question.",
			"What is it you are really asking?"],
		[	"Is that the real reason?",
			"What other reasons come to mind?",
			"Does that reason apply to anything else?",
			"If %1, what else must be true?"],
		[	"There are many times when no apology is needed.",
			"What feelings do you have when you apologize?"],
		[	"Hello... I am glad you could drop by today.",
			"Hi there... how are you today?",
			"Hello, how are you feeling today?"],
		[	"Do you doubt %1?",
			"Do you really think so?",
			"But you are not sure %1?"],
		[	"Tell me more about your friends.",
			"When you think of a friend, what comes to mind?",
			"Why don't you tell me about a childhood friend?"],
		[	"You seem quite sure.",
			"OK, but can you elaborate a bit?"],
		[	"Do you think it is %1?",
			"Perhaps it's %1 -- what do you think?",
			"If it were %1, what would you do?",
			"It could well be that %1."],
		[	"You seem very certain.",
			"If I told you that it probably is not %1, what would you feel?"],
		[	"What makes you think I can't %1?",
			"If I could %1, then what?",
			"Why do you ask if I can %1?"],
		[	"Perhaps you do not want to %1.",
			"Do you want to be able to %1?",
			"If you could %1, would you?"],
		[	"Why do you think I am %1?",
			"Does it please you to think that I'm %1?",
			"Perhaps you would like me to be %1.",
			"Perhaps you are really talking about yourself?"],
		[	"Why do you say I am %1?",
			"Why do you think I am %1?",
			"Are we talking about you, or me?"],
		[	"Do not you really %1?",
			"Why do not you %1?",
			"Do you want to %1?"],
		[	"Good, tell me more about these feelings.",
			"Do you often feel %1?",
			"When do you usually feel %1?",
			"When you feel %1, what do you do?"],
		[	"Why do you tell me that you've %1?",
			"Have you really %1?",
			"Now that you have %1, what will you do next?"],
		[	"Could you explain why you would %1?",
			"Why would you %1?",
			"Who else knows that you would %1?"],
		[	"Do you think there is %1?",
			"It is likely that there is %1.",
			"Would you like there to be %1?"],
		[	"I see, your %1.",
			"Why do you say that your %1?",
			"When your %1, how do you feel?"],
		[	"We should be discussing you, not me.",
			"Why do you say that about me?",
			"Why do you care whether I %1?"],
		[	"Why do not you tell me the reason why %1?",
			"Why do you think %1?" ],
		[	"What would it mean to you if you got %1?",
			"Why do you want %1?",
			"What would you do if you got %1?",
			"If you got %1, then what would you do?"],
		[	"Tell me more about your mother.",
			"What was your relationship with your mother like?",
			"How do you feel about your mother?",
			"How does this relate to your feelings today?",
			"Good family relations are important."],
		[	"Tell me more about your father.",
			"How did your father make you feel?",
			"How do you feel about your father?",
			"Does your relationship with your father relate to your feelings today?",
			"Do you have trouble showing affection with your family?"],
		[	"Did you have close friends as a child?",
			"What is your favorite childhood memory?",
			"Do you remember any dreams or nightmares from childhood?",
			"Did the other children sometimes tease you?",
			"How do you think your childhood experiences relate to your feelings today?"],
		[	"Thank you for talking with me.",
			"Good-bye.",
			"Thank you, that will be $150. Have a good day!"]
		]
		